#██╗  ██╗██╗████████╗████████╗██╗   ██╗
#██║ ██╔╝██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#█████╔╝ ██║   ██║      ██║    ╚████╔╝ 
#██╔═██╗ ██║   ██║      ██║     ╚██╔╝  
#██║  ██╗██║   ██║      ██║      ██║   
#╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝ 

font_size 11
window_padding_width 14
include theme.conf
confirm_os_window_close 0
cursor_trail 3 
cursor_trail_decay 0.1 0.4

font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
