theme = 'catppuccin'
editor = "nvim"
dir_editor = "nvim"
auto_check_update = true
cd_on_quit = false
default_open_file_preview = true
show_image_preview = true
show_panel_footer_info = true
default_directory = "."
file_size_use_si = false
default_sort_type = 0      # Default sort type (0: Name, 1: Size, 2: Date Modified, 3: Type).
sort_order_reversed = false
case_sensitive_sort = false
shell_close_on_success = false
debug = false
ignore_missing_fields = false

code_previewer = ''
nerdfont = true
show_select_icons = true
transparent_background = false
file_preview_width = 0
sidebar_width = 20

border_top = '─'
border_bottom = '─'
border_left = '│'
border_right = '│'
border_top_left = '╭'
border_top_right = '╮'
border_bottom_left = '╰'
border_bottom_right = '╯'
border_middle_left = '├'
border_middle_right = '┤'

metadata = false
enable_md5_checksum = false
zoxide_support = true
