# Plugins 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-vim 'session'
set -g default-command "${SHELL}"

# Mouse support
set -g mouse on

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "#11111b"

# Window style
set-window-option -g status-position bottom
set -wg automatic-rename on
set -g automatic-rename-format ''
set -g status-justify 'absolute-centre'
set -g @catppuccin_window_status_style 'custom'
set -g @catppuccin_window_number ""
set -g @catppuccin_window_text "#[fg=#{@thm_rosewater},bg=#{@thm_mantle}] #I#{?#{!=:#{window_name},},: #W ,}"
set -g @catppuccin_window_current_number ""
set -g @catppuccin_window_current_text "#[fg=#{@thm_mantle},bg=#{@thm_mauve}] #I#{?#{!=:#{window_name},},: #W ,}"

# Right and Left 
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
setw -g pane-border-status bottom
setw -g pane-border-format ""

# Set Index
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Leader key
set -g prefix C-Space 
unbind C-b
bind C-Space send-prefix

# Reload Config
unbind r 
bind r source-file ~/.config/tmux/tmux.conf

# Copy/Paste
set-window-option -g mode-keys vi 
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Tabs
bind v split-window -h -c "#{pane_current_path}"  
bind h split-window -v -c "#{pane_current_path}"

# Image Pass 
set -g allow-passthrough on
set -g set-clipboard on
set -g focus-events on

# Load 
run "~/.config/tmux/plugins/tmux/catppuccin.tmux"
run "~/.tmux/plugins/tpm/tpm" 
