# ██╗  ██╗██╗   ██╗██████╗ ██████╗ 
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗
# ██║  ██║   ██║   ██║     ██║  ██║
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝

source = $HOME/.config/hypr/modules/enva.conf
source = $HOME/.config/hypr/modules/monitor.conf
source = $HOME/.config/hypr/modules/autostart.conf
source = $HOME/.config/hypr/modules/input.conf
source = $HOME/.config/hypr/modules/animations.conf
source = $HOME/.config/hypr/modules/decor.conf
source = $HOME/.config/hypr/modules/window_rules.conf
source = $HOME/.config/hypr/modules/keybinds.conf
source = $HOME/.config/hypr/modules/plugins.conf
