## AUTOSTART 

exec-once = wl-paste --watch cliphist store
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = uwsm app -- swww-daemon 
exec-once = uwsm app -- pypr
exec-once = uwsm app -- hypridle 
exec-once = uwsm app -- tmux
exec-once = uwsm app -- hyprpanel
exec-once = uwsm app -- qs -c overview
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
