## DECORATIONS

general {
    gaps_in = 5
    gaps_out = 8
    gaps_workspaces = 50
    border_size = 2
    
    col.active_border = rgba(f5c2e7FF) rgba(cba6f7FF) 45deg
    col.inactive_border = rgba(585b70FF)
    layout = dwindle
}

decoration {
    rounding = 0
    active_opacity = 0.90
    inactive_opacity = 0.92
    blur{
        enabled = true
        size = 20 
        passes = 3
        new_optimizations = true
      }
}

dwindle {
    preserve_split = true       
    pseudotile = true
}

misc {
    disable_hyprland_logo = true
}
