## KEYBINDS

# Variables
$mainMod = SUPER
$scripts = ~/.config/scripts/user/
$dropTerm = wezterm start --class dropTerm
$mainTerm = wezterm start --class mainTerm

# Switch workspaces 
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Move active window to a workspace 
bind = ALT, 1, movetoworkspacesilent, 1
bind = ALT, 2, movetoworkspacesilent, 2
bind = ALT, 3, movetoworkspacesilent, 3
bind = ALT, 4, movetoworkspacesilent, 4
bind = ALT, 5, movetoworkspacesilent, 5
bind = ALT, 6, movetoworkspacesilent, 6
bind = ALT, 7, movetoworkspacesilent, 7
bind = ALT, 8, movetoworkspacesilent, 8
bind = ALT, 9, movetoworkspacesilent, 9

# Move/resize windows
bind = ALT, Tab, cyclenext
bind = ALT, Tab, bringactivetotop
bind = $mainMod, left,  movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up,    movefocus, u
bind = $mainMod, down,  movefocus, d
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod SHIFT, right, resizeactive, 30 0
bind = $mainMod SHIFT, left, resizeactive, -30 0
bind = $mainMod SHIFT, up, resizeactive, 0 -30
bind = $mainMod SHIFT, down, resizeactive, 0 30

# video play paues bindings
bind=,172,exec,playerctl play-pause
bind=,171,exec,playerctl next
bind=,173,exec,playerctl previous

# Volume and Brightness controls
bind = $mainMod, bracketright, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = $mainMod, bracketleft, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = $mainMod, M, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0
bind = $mainMod, apostrophe, exec, brightnessctl set +5%
bind = $mainMod, semicolon, exec, brightnessctl set 5%- 

# System Keybinds
bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen
bind = $mainMod, P, exec, hyprctl dispatch pin active 
bind = $mainMod SHIFT, L, exec, hyprctl dispatch exit
bind = $mainMod, H, exec, $scripts/hide.sh h 
bind = $mainMod SHIFT, H, exec, $scripts/hide.sh s
bind = $mainMod SHIFT, F, exec, $scripts/toggle_float.sh
bind = $mainMod , Grave, exec, $scripts/save_screen.sh  
bind = $mainMod SHIFT, Grave, exec, $scripts/save_area.sh
bind = $mainMod, D, exec, $scripts/menu.sh
bind = $mainMod, X, exec, $scripts/wallselect.sh
bind = $mainMod, PERIOD, exec, $scripts/emoji.sh
bind = $mainMod, COMMA, exec, $scripts/clipboard.sh
bind = $mainMod, RETURN, exec, $scripts/restart_bar.sh 

# Launching apps

bind = $mainMod, T, exec, uwsm app -- wezterm
bind = $mainMod, C, exec, uwsm app -- wezterm start nvim
bind = $mainMod, V, exec, uwsm app -- equibop
bind = $mainMod, E, exec, uwsm app -- nemo
bind = $mainMod, B, exec, uwsm app -- zen-browser
bind = $mainMod, O, exec, uwsm app -- obsidian
bind = $mainMod, L, exec, uwsm app -- hyprlock

# Scratchpads
bind = $mainMod, W, exec, uwsm app -- $dropTerm 
bind = $mainMod, R, exec, uwsm app -- $dropTerm yazi
bind = $mainMod, N, exec, uwsm app -- $dropTerm ncmpcpp
bind = $mainMod SHIFT, B, exec, uwsm app -- $mainTerm btop 

