# WindowRules
windowrule = float on, size 1400 850, center on, match:class ^(org.gnome.eog)$
windowrule = float on, size 1400 850, center on, match:class ^(org.gnome.Showtime)$
windowrule = float on, size 1200 700, center on, match:class ^(nemo)$
windowrule = float on, size 1200 450, move (360) (35), match:class ^(dropTerm)$
# windowrule = opaque on, match:class ^(equibop)$

# Portals
windowrule = float on, size 1200 700, center on, match:class ^(xdg-desktop-portal-gtk)$
windowrule = float on, size 1200 700, center on, match:class ^(xdg-desktop-portal-hyprland)$
windowrule = float on, size 1200 700, center on, match:class ^(xdg-desktop-portal)$
windowrule = float on, size 1200 700, center on, match:title ^(Add Torrents)$
windowrule = float on, size 1200 700, center on, match:title ^(Open Image)$
windowrule = float on, size 1200 700, center on, match:title ^(Choose a \.torrent file)$

# LayerRules
layerrule = no_anim on, match:namespace hyprpicker
layerrule = animation slide bottom, match:namespace dashboardmenu
layerrule = animation slide bottom, match:namespace audiomenu
layerrule = animation slide bottom, match:namespace mediamenu
layerrule = animation slide bottom, match:namespace bluetoothmenu
layerrule = animation slide bottom, match:namespace notificationsmenu
layerrule = animation slide bottom, match:namespace calendarmenu
layerrule = animation slide bottom, match:namespace powerdropdownmenu
layerrule = animation slide bottom, match:namespace networkmenu
layerrule = animation slide bottom, match:namespace energymenu
 


