# WindowRules

windowrulev2 = float, size 1400 850, center, class:^(org.gnome.eog)$
windowrulev2 = float, size 1400 850, center, class:^(org.gnome.Showtime)$
windowrulev2 = float, size 1200 700, center, class:^(nemo)$
windowrulev2 = float, size 1400 850, center, class:^(deluge)$
windowrulev2 = float, size 1200 450, move 360 35, title:^(kitten)$
# windowrulev2 = opaque, class:^(zen)$

# Portals
windowrulev2 = float, size 1200 700, center, class:^(xdg-desktop-portal-gtk)$
windowrulev2 = float, size 1200 700, center, class:^(xdg-desktop-portal-hyprland)$
windowrulev2 = float, size 1200 700, center, class:^(xdg-desktop-portal)$
windowrulev2 = float, size 1200 700, center, title:^(Add Torrents)$
windowrulev2 = float, size 1200 700, center, title:^(Open Image)$
windowrulev2 = float, size 1200 700, center, title:^(Choose a \.torrent file)$




