-- Create an autocommand for formatting Dart files on save
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   pattern = "*.dart",
--   callback = function()
--     vim.lsp.buf.format({ async = true })
--   end,
-- })
